scalar Day
scalar Date

interface Node {
  id: ID!
}

type Tag implements Node {
  id: ID!
  name: String!
  tagCount: Int!
}

type Stem implements Node {
  id: ID!
  createAt: Date!
  flowering: Boolean!
  title: String!
  tags: [Tag]!
  body: String!
  originLeaf: Leaf
  leaves: LeafConnection!
}

type StemConnection {
  nodes: [Stem]!
  totalCount: Int!
}

type Leaf implements Node {
  id: ID!
  createAt: Date!
  title: String!
  originStem: Stem!
  stems: StemConnection!
}

type LeafConnection {
  nodes: [Leaf]!
  totalCount: Int!
}

type Post implements Node {
  id: ID!
  day: Day!
  stems: StemConnection!
  leaves: LeafConnection!
}

type Panel {
  posts(limit: Int, earlyThan: Day, lateThan: Day): [Post]!
  stems(limit: Int): StemConnection!
  flowers(limit: Int): StemConnection!
  seeds(limit: Int): StemConnection!
  fruits(limit: Int): StemConnection!
  leaves(limit: Int): LeafConnection!
}

input createStemInput {
  specifiedDay: Day
  parentID: ID
  title: String
  flowering: Boolean
  tags: [String]!
  body: String!
}

type Query {
  node(id: ID!): Node

  panel: Panel!

  posts(limit: Int, earlyThan: Day, lateThan: Day): [Post]!
  post(day: Day!): Post

  matchedLeaves(matching: String!): [Leaf]!

  tags(limit: Int): [Tag]!
  matchedTags(matching: String!): [Tag]!
}

type Mutation {
  createStem(input: createStemInput!): Stem
}
